# Change these first
owner: runeforge-io # Your GitHub organization or username, where this repository lives
repo: runeforge-status # The name of this repository

sites:
  - name: Runeforge
    url: https://runeforge.dev/mods

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.runeforge.dev
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Status tracker for Runeforge services"
  introMessage: This is the official Runeforge services status/health tracker
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/runeforge-io

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
